### ISSUE TITLE
Local File Support?

### ISSUE THREAD

**Issue by kmanalo** [cyberaide/bookmanager#1]
Nice tool! Is there a syntax for specifying files local to a computer? 

Right now I have syntax of the form (say on Mac), based off the the sample yaml files:

```
git:
  "book": "file:///Users/me/repos/myrepo/doc/"
```

But this required the adding a local file adapter in the requests module which I did not particularly enjoy adding.  Perhaps I am trying too hard... 

Error from supplying standard path is:
```
requests.exceptions.MissingSchema: Invalid URL: '/Users/me/repos/myrepo/doc/README.md': No schema supplied. Perhaps you meant http:///Users/me/repos/myrepo/doc/README.md?
```

**Comment by laszewsk** [comment]
good idea! We originally only wanted to use http resources, but a local: would be quite useful also 
I wil try to implement soon.

**Comment by laszewsk** [comment]
Local file support has been experimentally added. Let us know if it does not work 

I inly tested https://github.com/cyberaide/bookmanager/blob/master/tests/local.yml

which seemed to wor
