### ISSUE TITLE
404 Error in Invitation Link in email

### ISSUE THREAD

**Issue by JLemon1** [cyberaide/bookmanager#2]
This is what I see when I click on the invitation link. I don't know if this is the place for this, but I thought I'd say it. Thanks.
![Capture](https://user-images.githubusercontent.com/31256525/64361715-1e05e100-cfdb-11e9-8f55-e43c7549318e.PNG)

**Comment by laszewsk** [comment]
This is unrelated to bookmanager and should be discussied in piazza so TAs can help
